### ISSUE TITLE
Line colorized if mut on beggining

### ISSUE THREAD

**Issue by TheChoconut** [DustLanguage/Dust_Prototype#1]
![image](https://user-images.githubusercontent.com/16463535/37258249-46f6fb6a-2575-11e8-94be-943731164096.png)

Line 2 should not be colorized!

The regex that should be fixed is [here](https://github.com/DustLanguage/Dust/blob/cd31c54e16c396b69749b405bc5a56040909be23/Dust.VSCode/client/dust.json#L78).

**Comment by Nufflee** [comment]
Moved to DustLanguage/Dust.VSCode#1.
