### ISSUE TITLE
Function parameters not working

### ISSUE THREAD

**Issue by TheChoconut** [DustLanguage/Dust_Prototype#7]
Adding parameters in function will result in an "Object is null" Exception.

**Comment by TheChoconut** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Functions](https://trello.com/c/MWnicHz9/1-functions)

**Comment by Nufflee** [comment]
This is partially fixed in fdfdc4ad45c90eacf097ae3763d82caff1208f38. Function parameters can be used in return statement but can't be accessed elsewhere.  New issue: #9.
